# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/general_test',
                'doc_host': 'https://JRSR92.github.io',
                'git_url': 'https://github.com/JRSR92/general_test',
                'lib_path': 'general_test'},
  'syms': {'general_test.core': {'general_test.core.foo': ('core.html#foo', 'general_test/core.py')}}}
